# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.10.0"

package:
  name: openfeature-sdk
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/o/openfeature-sdk/openfeature_sdk-${{ version }}.tar.gz
  sha256: 938c2540bdea4da3b01ef507517ee636f223a35abaaca845c5587e594151b052

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build ~=0.11.0
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - openfeature.hook
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/open-feature/python-sdk
  license: Apache-2.0
  license_file: LICENSE
  summary: Standardizing Feature Flagging for Everyone
  description: |
    Standardizing Feature Flagging for Everyone

extra:
  recipe-maintainers:
    - rxm7706
